# Generated by Django 3.1.6 on 2021-05-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nothing',
            field=models.CharField(default='', max_length=10),
        ),
    ]
