# Generated by Django 3.1.6 on 2021-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
