# Generated by Django 3.1.6 on 2021-05-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0002_post_nothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
