# Generated by Django 3.1.6 on 2021-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0003_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='general', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='holistic.Tag'),
        ),
    ]
