# Generated by Django 3.1.6 on 2021-05-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0003_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='post_summary',
        ),
    ]
