# Generated by Django 3.1.6 on 2021-05-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0004_auto_20210518_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nothing',
        ),
    ]
