# Generated by Django 3.1.6 on 2021-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0005_auto_20210518_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255),
        ),
    ]
