# Generated by Django 3.1.6 on 2021-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0007_auto_20210519_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
