# Generated by Django 3.1.6 on 2021-05-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0009_auto_20210513_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
